[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
anyhow = "1.0"
serde_json = "1.0"
serde = { version = "1.0.216", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
