[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25"
anyhow = "1.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
axum = { version = "0.7", features = ["multipart"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
